"""
Content Exporter — plain text and Markdown export utilities
"""

from datetime import datetime


def export_notes_txt(notes: dict) -> str:
    lines = [
        f"# {notes.get('title', 'Study Notes')}",
        f"Generated by StudyTube AI · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Overview",
        notes.get("overview", ""),
        "",
        "## Key Points",
    ]
    for pt in notes.get("keyPoints", []):
        lines.append(f"  • {pt}")
    lines.append("")

    for sec in notes.get("sections", []):
        lines.append(f"## {sec.get('heading', '')}")
        lines.append(sec.get("content", ""))
        for b in sec.get("bullets", []):
            lines.append(f"  → {b}")
        lines.append("")

    return "\n".join(lines)


def export_flashcards_txt(cards: list) -> str:
    lines = [
        "# Flashcards — StudyTube AI",
        f"Generated: {datetime.now().strftime('%Y-%m-%d')}",
        "",
    ]
    for i, card in enumerate(cards, 1):
        lines += [f"--- Card {i} ---", f"Q: {card.get('front', '')}", f"A: {card.get('back', '')}", ""]
    return "\n".join(lines)


def export_quiz_txt(questions: list) -> str:
    lines = ["# Quiz — StudyTube AI", ""]
    for i, q in enumerate(questions, 1):
        lines.append(f"Q{i}: {q.get('question', '')}")
        for j, opt in enumerate(q.get("options", []), 1):
            marker = "✓" if opt == q.get("correct") else " "
            lines.append(f"  {marker} {chr(64+j)}. {opt}")
        if q.get("explanation"):
            lines.append(f"  💡 {q['explanation']}")
        lines.append("")
    return "\n".join(lines)
